steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/tap-tap-bubblik-backend-4821/puzyrik/entitlements-api:v2'
      - '-f'
      - 'Puzyrik.Entitlements/Dockerfile'
      - '.'
images:
  - 'asia-east1-docker.pkg.dev/tap-tap-bubblik-backend-4821/puzyrik/entitlements-api:v2'